services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      abdilla.my.id:
        ipv4_address: 172.20.0.9
networks:
  abdilla.my.id:
    external: true
